# Gulp will use this configuration
paths:
  # Path to dist folder
  dist: "./lib/"
  # Source Locations
  src:
    js:
    - "./src/**/*.js"
    - "!./src/node_modules/**/*.js"
    html:
    - "./src/**/*.html"
entries: './src/sample/remote-server.js'
